### PR TITLE
Quickfix for Vote UI

### PR DESCRIPTION
**Pull request by bmino**
Hard-codes the known voting blocks for each proposal. This is extremely efficient to query for the creation event logs.

Upon a new proposal, the GOVERNANCE_PROPOSAL_BLOCKS constant would need to be updated

### CODE REVIEW

**Review by HariSeldon23 — APPROVED** [review]
It's a short term fix. Not great, but it means we can get it running.

**Review by benber86 — APPROVED** [review]

**Comment by dasconnor** [comment]
Tried to integrate this into master on the main repo with an additional fix to derive the blocknumber from the proposal rather than using hardcoded values. Ran out of time and still dealing with a bug. Would appreciate it if anyone else could jump in. https://github.com/pangolindex/interface/pull/34

**Comment by bmino** [comment]
This is still up there on my priorities. I'll take a look tonight

**Comment by bmino** [comment]
Closing this, as the issue was fully addressed in https://github.com/pangolindex/interface/pull/34 and https://github.com/pangolindex/interface/pull/35

**Pull request closed without merging**
